CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  nim VARCHAR(20) NOT NULL,
  batch SMALLINT,
  address VARCHAR(500),
  created_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS users_id_idx ON users ("id");
